#!/usr/bin/env python

import os
import sys

os.environ['DJANGO_SETTINGS_MODULE'] = 'base_app.settings'
sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi', 'carinscup'))
from distutils.sysconfig import get_python_lib
os.environ['PYTHON_EGG_CACHE'] = get_python_lib()

import django.core.wsgi

try:
    import pymysql
    pymysql.install_as_MySQLdb()
except ImportError:
    pass

application = django.core.wsgi.get_wsgi_application()
